#!/usr/bin/env bash
# MemPalace HTTP MCP server startup script (Linux/macOS)
# Usage: ./start-mempalace.sh
# Stops any existing mempalace process and starts a new one in HTTP MCP mode
# so cbmem-team can auto-sync drawers via POST /mcp + Bearer token.
#
# Token precedence:
#   1. MEMPALACE_TOKEN environment variable (if set)
#   2. Auto-generated by `mempalace serve` when binding a non-loopback host
#      (stored 0600 under ~/.mempalace/server/)
#
# When binding loopback (default 127.0.0.1), no token is required.
set -euo pipefail

# --- Configuration (override via env vars) -----------------------------------
MEMPALACE_BIN="${MEMPALACE_BIN:-}"       # e.g. "mempalace" or full path to the CLI
MEMPALACE_PATH="${MEMPALACE_PATH:-}"     # optional: palace directory
MEMPALACE_HOST="${MEMPALACE_HOST:-127.0.0.1}"
MEMPALACE_PORT="${MEMPALACE_PORT:-8765}"
MEMPALACE_TOKEN="${MEMPALACE_TOKEN:-}"   # empty = let `serve` decide

# --- Resolve the CLI binary --------------------------------------------------
use_module=0
if [ -z "$MEMPALACE_BIN" ]; then
    if command -v mempalace >/dev/null 2>&1; then
        MEMPALACE_BIN="mempalace"
    else
        MEMPALACE_BIN="python3"
        use_module=1
    fi
fi

# --- Stop existing process ---------------------------------------------------
if pgrep -f "mempalace.*serve" >/dev/null 2>&1; then
    echo "Stopping existing mempalace..."
    pkill -f "mempalace.*serve" || true
    sleep 1
fi

# --- Assemble args -----------------------------------------------------------
if [ "$use_module" -eq 1 ]; then
    mp_args=(-m mempalace serve --host "$MEMPALACE_HOST" --port "$MEMPALACE_PORT")
else
    mp_args=(serve --host "$MEMPALACE_HOST" --port "$MEMPALACE_PORT")
fi
if [ -n "$MEMPALACE_PATH" ]; then
    mp_args+=(--palace "$MEMPALACE_PATH")
fi
if [ -n "$MEMPALACE_TOKEN" ]; then
    mp_args+=(--token "$MEMPALACE_TOKEN")
fi

# --- Start -------------------------------------------------------------------
echo "Starting MemPalace HTTP MCP server..."
if [ "$use_module" -eq 1 ]; then
    echo "  bin   : $MEMPALACE_BIN (module)"
else
    echo "  bin   : $MEMPALACE_BIN"
fi
echo "  bind  : ${MEMPALACE_HOST}:${MEMPALACE_PORT}"
if [ -n "$MEMPALACE_PATH" ]; then
    echo "  palace: $MEMPALACE_PATH"
fi
if [ -n "$MEMPALACE_TOKEN" ]; then
    echo "  token : <provided>"
else
    echo "  token : auto (loopback = no auth)"
fi

nohup "$MEMPALACE_BIN" "${mp_args[@]}" >mempalace-stdout.log 2>mempalace-stderr.log &
MP_PID=$!

sleep 2

if kill -0 "$MP_PID" >/dev/null 2>&1; then
    echo "mempalace started successfully (PID $MP_PID)"
    echo ""
    echo "Client connect:"
    url="http://${MEMPALACE_HOST}:${MEMPALACE_PORT}/mcp"
    if [ -n "$MEMPALACE_TOKEN" ]; then
        echo "  cbmem-team: -mempalace-base $url -mempalace-token <token>"
    else
        echo "  cbmem-team: -mempalace-base $url"
    fi
    echo "  healthz   : curl http://${MEMPALACE_HOST}:${MEMPALACE_PORT}/healthz"
else
    echo "mempalace failed to start. Run manually:"
    echo "  \"$MEMPALACE_BIN\" ${mp_args[*]}"
    echo "See mempalace-stderr.log"
    exit 1
fi
