# MemPalace HTTP MCP server startup script (Windows)
# Usage: .\start-mempalace.ps1
# Stops any existing mempalace process and starts a new one in HTTP MCP mode
# so cbmem-team can auto-sync drawers via POST /mcp + Bearer token.
#
# Token precedence:
#   1. $env:MEMPALACE_TOKEN environment variable (if set)
#   2. Auto-generated by `mempalace serve` when binding a non-loopback host
#      (stored 0600 under ~/.mempalace/server/)
#
# When binding loopback (default 127.0.0.1), no token is required.

$ErrorActionPreference = "Stop"

# --- Configuration (override via env vars) -----------------------------------
$palaceBin    = $env:MEMPALACE_BIN       # e.g. "mempalace" or full path to the CLI
$palacePath   = $env:MEMPALACE_PATH      # optional: palace directory (overrides default)
$bindHost     = if ($env:MEMPALACE_HOST) { $env:MEMPALACE_HOST } else { "127.0.0.1" }
$port         = if ($env:MEMPALACE_PORT) { [int]$env:MEMPALACE_PORT } else { 8765 }
$token        = $env:MEMPALACE_TOKEN     # empty = let `serve` decide (auto for non-loopback)

# --- Resolve the CLI binary --------------------------------------------------
if (-not $palaceBin) {
    # Prefer a PATH-resolved `mempalace`; fall back to `python -m mempalace`.
    $resolved = Get-Command mempalace -ErrorAction SilentlyContinue
    if ($resolved) {
        $palaceBin = $resolved.Source
    } else {
        $palaceBin = "python"
        $useModule = $true
    }
}

# --- Stop existing process ---------------------------------------------------
$existing = Get-Process -Name "mempalace*" -ErrorAction SilentlyContinue |
    Where-Object { $_.CommandLine -match "serve|--transport" }
if ($existing) {
    Write-Host "Stopping existing mempalace (PID $($existing.Id))..." -ForegroundColor Yellow
    $existing | Stop-Process -Force
    Start-Sleep -Seconds 1
}

# --- Assemble args -----------------------------------------------------------
if ($useModule) {
    $mpArgs = @("-m", "mempalace", "serve", "--host", $bindHost, "--port", $port)
} else {
    $mpArgs = @("serve", "--host", $bindHost, "--port", $port)
}
if ($palacePath) {
    $mpArgs += @("--palace", $palacePath)
}
if ($token) {
    $mpArgs += @("--token", $token)
}

# --- Start -------------------------------------------------------------------
Write-Host "Starting MemPalace HTTP MCP server..." -ForegroundColor Green
Write-Host "  bin   : $palaceBin$(if ($useModule) {' (module)'})"
Write-Host "  bind  : ${bindHost}:${port}"
if ($palacePath) { Write-Host "  palace: $palacePath" }
if ($token)      { Write-Host "  token : <provided>" } else { Write-Host "  token : auto (loopback = no auth)" }

Start-Process -FilePath $palaceBin `
    -ArgumentList $mpArgs `
    -WorkingDirectory (Get-Location).Path

Start-Sleep -Seconds 2

$proc = Get-Process -Name "mempalace*","python*" -ErrorAction SilentlyContinue |
    Where-Object { $_.CommandLine -match "mempalace.*serve" } |
    Select-Object -First 1
if ($proc) {
    Write-Host "mempalace started successfully (PID $($proc.Id))" -ForegroundColor Green
    Write-Host ""
    Write-Host "Client connect:" -ForegroundColor Cyan
    $url = "http://${bindHost}:${port}/mcp"
    if ($token) {
        Write-Host "  cbmem-team: -mempalace-base $url -mempalace-token <token>"
    } else {
        Write-Host "  cbmem-team: -mempalace-base $url"
    }
    Write-Host "  healthz   : curl http://${bindHost}:${port}/healthz"
} else {
    Write-Host "mempalace failed to start. Run manually:" -ForegroundColor Red
    Write-Host "  $palaceBin $($mpArgs -join ' ')"
}
