#!/bin/bash
# qa-dev skill 快速执行脚本

echo "=============================================="
echo "  /qa-dev Skill - QA测试与自动开发二合一"
echo "=============================================="
echo ""
echo "用法示例:"
echo "  /qa-dev --file docs/scene/scene-template.md --module SYS-01"
echo "  /qa-dev --test-only --file docs/scene/scene-template.md --module SYS-01"
echo "  /qa-dev --dev-only --module SYS-01"
echo ""
echo "参数说明:"
echo "  --file       测试场景文件路径"
echo "  --module     指定模块ID (如 SYS-01)"
echo "  --scenario   指定场景章节 (如 5.1.2)"
echo "  --test-only  仅测试不开发"
echo "  --dev-only  仅开发不测试"
echo "  --batch      批量处理所有模块"
echo ""
echo "执行流程:"
echo "  1. Phase 1: QA测试 (自动化)"
echo "  2. Phase 2: 自动开发 (如发现未开发)"
echo "  3. Phase 3: 重新验证"
echo ""
