-- Auto-generated by tools/cbmem-team/deploy/sql/dump_sql.py — DO NOT EDIT BY HAND.
-- Canonical source: tools/cbmem-team/internal/console/db.go + tools.go + bp.go + workflow.go + repo_pipeline.go.
-- To regenerate after schema/seed changes, run:
--     python tools/cbmem-team/deploy/sql/dump_sql.py
-- and re-verify by running `cbmem-team migrate` against a fresh DB.

-- =====================================================================
-- cbmem-team console — SQLite schema (v2)
-- =====================================================================
-- Idempotent. Run with:  sqlite3 console.db < schema.sql

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

-- ----- legacy v1 (CON-01..CON-05) -----

CREATE TABLE IF NOT EXISTS users (
            id TEXT PRIMARY KEY,
            display_name TEXT,
            project_paths TEXT,
            max_procs INTEGER,
            disabled INTEGER DEFAULT 0,
            created_at DATETIME,
            updated_at DATETIME
        );

CREATE TABLE IF NOT EXISTS projects (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            path TEXT NOT NULL UNIQUE,
            wing TEXT,
            mcp_bin TEXT,
            user_id TEXT,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            deleted INTEGER DEFAULT 0
        );

CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id);

CREATE TABLE IF NOT EXISTS sessions (
            id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL,
            project_id TEXT,
            project_path TEXT NOT NULL,
            started_at DATETIME NOT NULL,
            ended_at DATETIME,
            tool_count INTEGER DEFAULT 0,
            turn_count INTEGER DEFAULT 0,
            summary TEXT
        );

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

CREATE INDEX IF NOT EXISTS idx_sessions_project ON sessions(project_id);

CREATE INDEX IF NOT EXISTS idx_sessions_started ON sessions(started_at DESC);

CREATE TABLE IF NOT EXISTS session_turns (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id TEXT NOT NULL,
            turn_no INTEGER NOT NULL,
            role TEXT NOT NULL,
            content TEXT NOT NULL,
            tools_json TEXT,
            ts DATETIME NOT NULL
        );

CREATE INDEX IF NOT EXISTS idx_session_turns_session ON session_turns(session_id);

CREATE TABLE IF NOT EXISTS summarize_tasks (
            id TEXT PRIMARY KEY,
            user_id TEXT,
            source_ids TEXT,
            depth TEXT,
            target_wing TEXT,
            status TEXT NOT NULL,
            result_json TEXT,
            created_at DATETIME NOT NULL,
            finished_at DATETIME
        );

CREATE TABLE IF NOT EXISTS distill_tasks (
            id TEXT PRIMARY KEY,
            user_id TEXT,
            source_ids TEXT,
            rules_json TEXT,
            status TEXT NOT NULL,
            result_json TEXT,
            mempalace_synced INTEGER DEFAULT 0,
            target_wing TEXT,
            created_at DATETIME NOT NULL,
            finished_at DATETIME
        );

CREATE TABLE IF NOT EXISTS console_sessions (
            id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL,
            created_at DATETIME NOT NULL,
            expires_at DATETIME NOT NULL,
            last_seen_at DATETIME,
            ip TEXT,
            ua TEXT
        );

CREATE INDEX IF NOT EXISTS idx_console_sessions_expires ON console_sessions(expires_at);

-- ----- M1 tool_directory + tool_invocation_logs -----

CREATE TABLE IF NOT EXISTS tool_directory (
                    tool_id TEXT PRIMARY KEY,
                    track TEXT NOT NULL,
                    category TEXT NOT NULL,
                    name TEXT NOT NULL,
                    signature TEXT,
                    status TEXT NOT NULL DEFAULT 'active',
                    priority INTEGER NOT NULL DEFAULT 5,
                    rate_limit_json TEXT,
                    related_halls_json TEXT,
                    related_wings_json TEXT,
                    version TEXT NOT NULL DEFAULT '1.0.0',
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL
                );

CREATE INDEX IF NOT EXISTS idx_tool_directory_track ON tool_directory(track, category);

CREATE INDEX IF NOT EXISTS idx_tool_directory_status ON tool_directory(status);

CREATE TABLE IF NOT EXISTS tool_invocation_logs (
                    invocation_id TEXT PRIMARY KEY,
                    user_id TEXT NOT NULL,
                    project_id TEXT,
                    project_path TEXT,
                    tool_id TEXT NOT NULL,
                    transport TEXT NOT NULL DEFAULT 'stdio',
                    args_json TEXT,
                    response_json TEXT,
                    started_at DATETIME NOT NULL,
                    ended_at DATETIME,
                    latency_ms INTEGER,
                    error_code TEXT,
                    timeout_flag INTEGER DEFAULT 0,
                    workflow_run_id TEXT,
                    blast_radius_json TEXT,
                    affected_drawers_json TEXT,
                    affected_halls_json TEXT,
                    affected_adrs_json TEXT,
                    wing_unauthorized_json TEXT,
                    client_ip TEXT,
                    jwt_sub TEXT
                );

CREATE INDEX IF NOT EXISTS idx_inv_user_started ON tool_invocation_logs(user_id, started_at);

CREATE INDEX IF NOT EXISTS idx_inv_tool_started ON tool_invocation_logs(tool_id, started_at);

CREATE INDEX IF NOT EXISTS idx_inv_project_started ON tool_invocation_logs(project_id, started_at);

CREATE INDEX IF NOT EXISTS idx_inv_workflow ON tool_invocation_logs(workflow_run_id);

CREATE INDEX IF NOT EXISTS idx_inv_error ON tool_invocation_logs(error_code);

-- ----- M2 best_practices + bp_versions -----

CREATE TABLE IF NOT EXISTS best_practices (
                    id TEXT PRIMARY KEY,
                    title TEXT NOT NULL,
                    category TEXT NOT NULL,
                    track TEXT NOT NULL CHECK (track IN ('A','B','J')),
                    tools TEXT NOT NULL DEFAULT '[]',
                    related_halls TEXT NOT NULL DEFAULT '[]',
                    related_wings TEXT NOT NULL DEFAULT '[]',
                    scenes TEXT NOT NULL DEFAULT '[]',
                    priority TEXT NOT NULL DEFAULT 'P3',
                    status TEXT NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft','published','deprecated','review_due')),
                    version INTEGER NOT NULL DEFAULT 1,
                    created_by TEXT NOT NULL,
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL,
                    review_due DATE NOT NULL,
                    source TEXT NOT NULL DEFAULT 'manual',
                    body TEXT NOT NULL
                );

CREATE INDEX IF NOT EXISTS idx_bp_status_priority ON best_practices(status, priority);

CREATE INDEX IF NOT EXISTS idx_bp_track_category ON best_practices(track, category);

CREATE INDEX IF NOT EXISTS idx_bp_tools_first ON best_practices(json_extract(tools, '$[0]'));

CREATE TABLE IF NOT EXISTS bp_versions (
                    bp_id TEXT NOT NULL,
                    version INTEGER NOT NULL,
                    snapshot_json TEXT NOT NULL,
                    changed_by TEXT NOT NULL,
                    change_note TEXT,
                    created_at DATETIME NOT NULL,
                    PRIMARY KEY (bp_id, version)
                );

CREATE INDEX IF NOT EXISTS idx_bpv_created ON bp_versions(bp_id, created_at);

-- ----- M3 workflows + workflow_runs + tickets -----

CREATE TABLE IF NOT EXISTS workflows (
                    workflow_id TEXT PRIMARY KEY,
                    name TEXT NOT NULL,
                    description TEXT,
                    track TEXT NOT NULL DEFAULT 'J',
                    category TEXT NOT NULL DEFAULT 'governance',
                    nodes_json TEXT NOT NULL,
                    entry_id TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'draft',
                    version INTEGER NOT NULL DEFAULT 1,
                    created_by TEXT NOT NULL DEFAULT 'anonymous',
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL
                );

CREATE INDEX IF NOT EXISTS idx_workflow_status ON workflows(status, category);

CREATE TABLE IF NOT EXISTS workflow_versions (
                    workflow_id TEXT NOT NULL,
                    version INTEGER NOT NULL,
                    snapshot_json TEXT NOT NULL,
                    changed_by TEXT NOT NULL DEFAULT 'anonymous',
                    change_note TEXT,
                    created_at DATETIME NOT NULL,
                    PRIMARY KEY (workflow_id, version)
                );

CREATE TABLE IF NOT EXISTS workflow_runs (
                    run_id TEXT PRIMARY KEY,
                    workflow_id TEXT NOT NULL,
                    version INTEGER NOT NULL,
                    triggered_by TEXT NOT NULL,
                    project_path TEXT,
                    dry_run INTEGER NOT NULL DEFAULT 0,
                    status TEXT NOT NULL DEFAULT 'pending',
                    started_at DATETIME NOT NULL,
                    ended_at DATETIME,
                    step_count INTEGER NOT NULL DEFAULT 0,
                    step_history_json TEXT,
                    error TEXT
                );

CREATE INDEX IF NOT EXISTS idx_wfrun_workflow ON workflow_runs(workflow_id, started_at);

CREATE INDEX IF NOT EXISTS idx_wfrun_status ON workflow_runs(status, started_at);

CREATE INDEX IF NOT EXISTS idx_wfrun_trigger ON workflow_runs(triggered_by, started_at);

CREATE TABLE IF NOT EXISTS tickets (
                    ticket_id TEXT PRIMARY KEY,
                    source TEXT NOT NULL DEFAULT 'manual',
                    invocation_id TEXT,
                    tool_id TEXT NOT NULL,
                    user_id TEXT,
                    severity TEXT NOT NULL DEFAULT 'medium',
                    status TEXT NOT NULL DEFAULT 'open',
                    title TEXT NOT NULL,
                    detail_json TEXT,
                    resolution_note TEXT,
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL
                );

CREATE INDEX IF NOT EXISTS idx_ticket_status ON tickets(status, created_at);

CREATE INDEX IF NOT EXISTS idx_ticket_invocation ON tickets(invocation_id);

-- ----- M4 repo_pipelines + bp_candidates -----

CREATE TABLE IF NOT EXISTS repo_pipelines (
                    pipeline_id TEXT PRIMARY KEY,
                    name TEXT NOT NULL,
                    source TEXT NOT NULL DEFAULT 'local',
                    target TEXT NOT NULL,
                    cron_expr TEXT,
                    threshold REAL NOT NULL DEFAULT 0.7,
                    status TEXT NOT NULL DEFAULT 'draft',
                    created_by TEXT NOT NULL DEFAULT 'anonymous',
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL
                );

CREATE INDEX IF NOT EXISTS idx_rp_status ON repo_pipelines(status, source);

CREATE TABLE IF NOT EXISTS repo_pipeline_runs (
                    run_id TEXT PRIMARY KEY,
                    pipeline_id TEXT NOT NULL,
                    stage_status TEXT,
                    items_ingested INTEGER NOT NULL DEFAULT 0,
                    items_parsed INTEGER NOT NULL DEFAULT 0,
                    items_graded INTEGER NOT NULL DEFAULT 0,
                    items_accepted INTEGER NOT NULL DEFAULT 0,
                    status TEXT NOT NULL DEFAULT 'pending',
                    started_at DATETIME NOT NULL,
                    ended_at DATETIME,
                    error TEXT
                );

CREATE INDEX IF NOT EXISTS idx_rprun_pipeline ON repo_pipeline_runs(pipeline_id, started_at);

CREATE INDEX IF NOT EXISTS idx_rprun_status ON repo_pipeline_runs(status, started_at);

CREATE TABLE IF NOT EXISTS bp_candidates (
                    candidate_id TEXT PRIMARY KEY,
                    pipeline_id TEXT NOT NULL,
                    run_id TEXT NOT NULL,
                    title TEXT NOT NULL,
                    body TEXT NOT NULL,
                    grade_score REAL NOT NULL DEFAULT 0.0,
                    source_url TEXT,
                    tags_json TEXT,
                    status TEXT NOT NULL DEFAULT 'draft',
                    merged_bp_id TEXT,
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL
                );

CREATE INDEX IF NOT EXISTS idx_bpc_status ON bp_candidates(status, created_at);

CREATE INDEX IF NOT EXISTS idx_bpc_run ON bp_candidates(run_id);

CREATE INDEX IF NOT EXISTS idx_bpc_pipeline ON bp_candidates(pipeline_id);

