-- Auto-generated by tools/cbmem-team/deploy/sql/dump_sql.py — DO NOT EDIT BY HAND.
-- Canonical source: tools/cbmem-team/internal/console/db.go + tools.go + bp.go + workflow.go + repo_pipeline.go.
-- To regenerate after schema/seed changes, run:
--     python tools/cbmem-team/deploy/sql/dump_sql.py
-- and re-verify by running `cbmem-team migrate` against a fresh DB.

-- =====================================================================
-- cbmem-team console — MySQL 8.0 schema (v2)
-- =====================================================================
-- Idempotent for CREATE TABLE (uses IF NOT EXISTS) and CREATE VIEW
-- (uses DROP+CREATE since MySQL has no CREATE VIEW IF NOT EXISTS).
-- CREATE INDEX has no IF NOT EXISTS in MySQL 8.0, so the migration
-- entry point probes information_schema.statistics instead. The SQL
-- files here are written for fresh databases; on existing databases,
-- run `cbmem-team migrate` so the probe-based path applies.

-- Legacy 7 tables -----------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
        id VARCHAR(128) NOT NULL PRIMARY KEY,
        display_name VARCHAR(255),
        project_paths TEXT,
        max_procs INT,
        disabled TINYINT(1) DEFAULT 0,
        created_at DATETIME,
        updated_at DATETIME
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projects (
        id VARCHAR(128) NOT NULL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        path VARCHAR(512) NOT NULL UNIQUE,
        wing VARCHAR(128),
        mcp_bin VARCHAR(512),
        user_id VARCHAR(128),
        created_at DATETIME NOT NULL,
        updated_at DATETIME NOT NULL,
        deleted TINYINT(1) DEFAULT 0
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sessions (
        id VARCHAR(128) NOT NULL PRIMARY KEY,
        user_id VARCHAR(128) NOT NULL,
        project_id VARCHAR(128),
        project_path VARCHAR(512) NOT NULL,
        started_at DATETIME NOT NULL,
        ended_at DATETIME,
        tool_count INT DEFAULT 0,
        turn_count INT DEFAULT 0,
        summary TEXT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS session_turns (
        id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        session_id VARCHAR(128) NOT NULL,
        turn_no INT NOT NULL,
        role VARCHAR(32) NOT NULL,
        content TEXT NOT NULL,
        tools_json TEXT,
        ts DATETIME NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS summarize_tasks (
        id VARCHAR(128) NOT NULL PRIMARY KEY,
        user_id VARCHAR(128),
        source_ids TEXT,
        depth VARCHAR(32),
        target_wing VARCHAR(128),
        status VARCHAR(32) NOT NULL,
        result_json LONGTEXT,
        created_at DATETIME NOT NULL,
        finished_at DATETIME
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS distill_tasks (
        id VARCHAR(128) NOT NULL PRIMARY KEY,
        user_id VARCHAR(128),
        source_ids TEXT,
        rules_json LONGTEXT,
        status VARCHAR(32) NOT NULL,
        result_json LONGTEXT,
        mempalace_synced TINYINT(1) DEFAULT 0,
        target_wing VARCHAR(128),
        created_at DATETIME NOT NULL,
        finished_at DATETIME
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS console_sessions (
        id VARCHAR(128) NOT NULL PRIMARY KEY,
        user_id VARCHAR(128) NOT NULL,
        created_at DATETIME NOT NULL,
        expires_at DATETIME NOT NULL,
        last_seen_at DATETIME,
        ip VARCHAR(64),
        ua VARCHAR(512)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Legacy indexes ------------------------------------------------------

-- projects.idx_projects_user
CREATE INDEX idx_projects_user ON projects(user_id);

-- sessions.idx_sessions_user
CREATE INDEX idx_sessions_user ON sessions(user_id);

-- sessions.idx_sessions_project
CREATE INDEX idx_sessions_project ON sessions(project_id);

-- sessions.idx_sessions_started
CREATE INDEX idx_sessions_started ON sessions(started_at DESC);

-- session_turns.idx_session_turns_session
CREATE INDEX idx_session_turns_session ON session_turns(session_id);

-- console_sessions.idx_console_sessions_expires
CREATE INDEX idx_console_sessions_expires ON console_sessions(expires_at);

-- M1..M4 -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tool_directory (
                    tool_id VARCHAR(128) NOT NULL PRIMARY KEY,
                    track VARCHAR(64) NOT NULL,
                    category VARCHAR(64) NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    signature TEXT,
                    status VARCHAR(32) NOT NULL DEFAULT 'active',
                    priority INT NOT NULL DEFAULT 5,
                    rate_limit_json JSON,
                    related_halls_json JSON,
                    related_wings_json JSON,
                    version VARCHAR(32) NOT NULL DEFAULT '1.0.0',
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tool_invocation_logs (
                    invocation_id VARCHAR(64) NOT NULL PRIMARY KEY,
                    user_id VARCHAR(128) NOT NULL,
                    project_id VARCHAR(128),
                    project_path VARCHAR(512),
                    tool_id VARCHAR(128) NOT NULL,
                    transport VARCHAR(16) NOT NULL DEFAULT 'stdio',
                    args_json LONGTEXT,
                    response_json LONGTEXT,
                    started_at DATETIME(3) NOT NULL,
                    ended_at DATETIME(3),
                    latency_ms INT,
                    error_code VARCHAR(64),
                    timeout_flag TINYINT(1) DEFAULT 0,
                    workflow_run_id VARCHAR(64),
                    blast_radius_json LONGTEXT,
                    affected_drawers_json LONGTEXT,
                    affected_halls_json LONGTEXT,
                    affected_adrs_json LONGTEXT,
                    wing_unauthorized_json LONGTEXT,
                    client_ip VARCHAR(64),
                    jwt_sub VARCHAR(128)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_tool_directory_track ON tool_directory(track, category);

CREATE INDEX idx_tool_directory_status ON tool_directory(status);

CREATE INDEX idx_inv_user_started ON tool_invocation_logs(user_id, started_at);

CREATE INDEX idx_inv_tool_started ON tool_invocation_logs(tool_id, started_at);

CREATE INDEX idx_inv_project_started ON tool_invocation_logs(project_id, started_at);

CREATE INDEX idx_inv_workflow ON tool_invocation_logs(workflow_run_id);

CREATE INDEX idx_inv_error ON tool_invocation_logs(error_code);

CREATE TABLE IF NOT EXISTS best_practices (
                    id VARCHAR(64) NOT NULL PRIMARY KEY,
                    title VARCHAR(160) NOT NULL,
                    category VARCHAR(32) NOT NULL,
                    track VARCHAR(8) NOT NULL,
                    tools JSON NOT NULL,
                    related_halls JSON NOT NULL,
                    related_wings JSON NOT NULL,
                    scenes JSON NOT NULL,
                    priority VARCHAR(8) NOT NULL DEFAULT 'P3',
                    status VARCHAR(16) NOT NULL DEFAULT 'draft',
                    version INT NOT NULL DEFAULT 1,
                    created_by VARCHAR(128) NOT NULL,
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL,
                    review_due DATE NOT NULL,
                    source VARCHAR(64) NOT NULL DEFAULT 'manual',
                    body LONGTEXT NOT NULL,
                    CHECK (track IN ('A','B','J')),
                    CHECK (status IN ('draft','published','deprecated','review_due'))
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bp_versions (
                    bp_id VARCHAR(64) NOT NULL,
                    version INT NOT NULL,
                    snapshot_json LONGTEXT NOT NULL,
                    changed_by VARCHAR(128) NOT NULL,
                    change_note VARCHAR(512),
                    created_at DATETIME NOT NULL,
                    PRIMARY KEY (bp_id, version)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_bp_status_priority ON best_practices(status, priority);

CREATE INDEX idx_bp_track_category ON best_practices(track, category);

CREATE INDEX idx_bp_tools_mv ON best_practices((CAST(tools AS CHAR(64) ARRAY)));

CREATE INDEX idx_bpv_created ON bp_versions(bp_id, created_at);

CREATE TABLE IF NOT EXISTS workflows (
                    workflow_id VARCHAR(64) NOT NULL PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    description TEXT,
                    track VARCHAR(8) NOT NULL DEFAULT 'J',
                    category VARCHAR(64) NOT NULL DEFAULT 'governance',
                    nodes_json LONGTEXT NOT NULL,
                    entry_id VARCHAR(64) NOT NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'draft',
                    version INT NOT NULL DEFAULT 1,
                    created_by VARCHAR(128) NOT NULL DEFAULT 'anonymous',
                    created_at DATETIME(3) NOT NULL,
                    updated_at DATETIME(3) NOT NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workflow_versions (
                    workflow_id VARCHAR(64) NOT NULL,
                    version INT NOT NULL,
                    snapshot_json LONGTEXT NOT NULL,
                    changed_by VARCHAR(128) NOT NULL DEFAULT 'anonymous',
                    change_note TEXT,
                    created_at DATETIME(3) NOT NULL,
                    PRIMARY KEY (workflow_id, version)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workflow_runs (
                    run_id VARCHAR(64) NOT NULL PRIMARY KEY,
                    workflow_id VARCHAR(64) NOT NULL,
                    version INT NOT NULL,
                    triggered_by VARCHAR(128) NOT NULL,
                    project_path VARCHAR(512),
                    dry_run TINYINT(1) NOT NULL DEFAULT 0,
                    status VARCHAR(16) NOT NULL DEFAULT 'pending',
                    started_at DATETIME(3) NOT NULL,
                    ended_at DATETIME(3),
                    step_count INT NOT NULL DEFAULT 0,
                    step_history_json LONGTEXT,
                    error TEXT
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tickets (
                    ticket_id VARCHAR(64) NOT NULL PRIMARY KEY,
                    source VARCHAR(64) NOT NULL DEFAULT 'manual',
                    invocation_id VARCHAR(64),
                    tool_id VARCHAR(128) NOT NULL,
                    user_id VARCHAR(128),
                    severity VARCHAR(16) NOT NULL DEFAULT 'medium',
                    status VARCHAR(16) NOT NULL DEFAULT 'open',
                    title VARCHAR(255) NOT NULL,
                    detail_json LONGTEXT,
                    resolution_note TEXT,
                    created_at DATETIME(3) NOT NULL,
                    updated_at DATETIME(3) NOT NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_workflow_status ON workflows(status, category);

CREATE INDEX idx_wfrun_workflow ON workflow_runs(workflow_id, started_at);

CREATE INDEX idx_wfrun_status ON workflow_runs(status, started_at);

CREATE INDEX idx_wfrun_trigger ON workflow_runs(triggered_by, started_at);

CREATE INDEX idx_ticket_status ON tickets(status, created_at);

CREATE INDEX idx_ticket_invocation ON tickets(invocation_id);

DROP VIEW IF EXISTS v_high_risk_invocations_7d;

CREATE VIEW v_high_risk_invocations_7d AS
                SELECT
                    invocation_id, user_id, project_id, tool_id, transport,
                    started_at, latency_ms, error_code,
                    affected_halls_json, affected_adrs_json, blast_radius_json
                FROM tool_invocation_logs
                WHERE started_at >= (NOW() - INTERVAL 7 DAY)
                  AND (
                    JSON_LENGTH(affected_halls_json) > 0
                    OR JSON_LENGTH(affected_adrs_json) > 0
                    OR JSON_LENGTH(blast_radius_json) > 0
                    OR error_code IN ('UPSTREAM_ERROR','FORBIDDEN','TIMEOUT')
                  );

CREATE TABLE IF NOT EXISTS repo_pipelines (
                    pipeline_id VARCHAR(64) NOT NULL PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    source VARCHAR(16) NOT NULL DEFAULT 'local',
                    target VARCHAR(1024) NOT NULL,
                    cron_expr VARCHAR(64),
                    threshold DOUBLE NOT NULL DEFAULT 0.7,
                    status VARCHAR(16) NOT NULL DEFAULT 'draft',
                    created_by VARCHAR(128) NOT NULL DEFAULT 'anonymous',
                    created_at DATETIME(3) NOT NULL,
                    updated_at DATETIME(3) NOT NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS repo_pipeline_runs (
                    run_id VARCHAR(64) NOT NULL PRIMARY KEY,
                    pipeline_id VARCHAR(64) NOT NULL,
                    stage_status JSON,
                    items_ingested INT NOT NULL DEFAULT 0,
                    items_parsed INT NOT NULL DEFAULT 0,
                    items_graded INT NOT NULL DEFAULT 0,
                    items_accepted INT NOT NULL DEFAULT 0,
                    status VARCHAR(16) NOT NULL DEFAULT 'pending',
                    started_at DATETIME(3) NOT NULL,
                    ended_at DATETIME(3),
                    error TEXT
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bp_candidates (
                    candidate_id VARCHAR(64) NOT NULL PRIMARY KEY,
                    pipeline_id VARCHAR(64) NOT NULL,
                    run_id VARCHAR(64) NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    body LONGTEXT NOT NULL,
                    grade_score DOUBLE NOT NULL DEFAULT 0.0,
                    source_url VARCHAR(1024),
                    tags_json JSON,
                    status VARCHAR(16) NOT NULL DEFAULT 'draft',
                    merged_bp_id VARCHAR(64),
                    created_at DATETIME(3) NOT NULL,
                    updated_at DATETIME(3) NOT NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_rp_status ON repo_pipelines(status, source);

CREATE INDEX idx_rprun_pipeline ON repo_pipeline_runs(pipeline_id, started_at);

CREATE INDEX idx_rprun_status ON repo_pipeline_runs(status, started_at);

CREATE INDEX idx_bpc_status ON bp_candidates(status, created_at);

CREATE INDEX idx_bpc_run ON bp_candidates(run_id);

CREATE INDEX idx_bpc_pipeline ON bp_candidates(pipeline_id);

DROP VIEW IF EXISTS v_repo_pipeline_success_rate_7d;

CREATE VIEW v_repo_pipeline_success_rate_7d AS
                SELECT
                    pipeline_id,
                    SUM(CASE WHEN status = 'succeeded' THEN 1 ELSE 0 END) AS ok_runs,
                    COUNT(*) AS total_runs,
                    ROUND(SUM(CASE WHEN status = 'succeeded' THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 3) AS success_rate,
                    MAX(started_at) AS last_started_at
                FROM repo_pipeline_runs
                WHERE started_at >= (NOW() - INTERVAL 7 DAY)
                GROUP BY pipeline_id;

