-- Auto-generated by tools/cbmem-team/deploy/sql/dump_sql.py — DO NOT EDIT BY HAND.
-- Canonical source: tools/cbmem-team/internal/console/tools.go (ToolSeed49).
-- To regenerate after schema/seed changes, run:
--     python tools/cbmem-team/deploy/sql/dump_sql.py
-- and re-verify by running `cbmem-team migrate` against a fresh DB.

-- =====================================================================
-- cbmem-team console — initial data (MySQL 8.0)
-- =====================================================================
-- Run AFTER schema-mysql.sql. Use:
--     mysql console < schema-mysql.sql
--     mysql console < seed-mysql.sql
-- Then `cbmem-team migrate-seed` for BP/workflow seeds.

SET autocommit=0;
START TRANSACTION;

-- ----- tool_directory (49 rows) -----

INSERT INTO tool_directory
    (tool_id, track, category, name, signature, status, priority, version, created_at, updated_at)
VALUES
    ('mempalace_status','A','read','Status','system_state','active',1,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_list_wings','A','read','List wings','scope','active',1,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_list_rooms','A','read','List rooms','wing_id','active',2,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_search','A','read','Semantic search','query','active',1,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_recall','A','read','Fuzzy recall','query','active',2,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_wing_info','A','read','Wing info','wing_id','active',3,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_list_halls','A','read','List halls','scope','active',2,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_list_drawers','A','read','List drawers','hall_id','active',2,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_view_drawer','A','read','View drawer','drawer_id','active',1,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_get_context','A','read','Get context bundle','wing_ids[]','active',2,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_add_drawer','A','write','Add drawer','drawer{original,context}','active',3,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_checkpoint','A','write','Checkpoint session','session_id','active',4,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_mine','A','write','Mine project files','path,wing_id','active',5,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_update_drawer','A','write','Update drawer','drawer_id,body','active',4,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_delete_drawer','A','write','Delete drawer','drawer_id','active',6,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_tag_drawer','A','write','Tag drawer','drawer_id,tags[]','active',5,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_create_wing','A','admin','Create wing','wing_name','active',5,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_create_room','A','admin','Create room','wing_id,room_name','active',6,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_request_access','A','admin','Request access','wing_id','active',7,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_config','A','admin','Get/set config','key,value','active',6,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_stats','A','admin','Stats','scope','active',6,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_export','A','admin','Export data','wing_id,format','active',7,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_grant_access','A','admin','Grant access','wing_id,user_id','active',6,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_revoke_access','A','admin','Revoke access','wing_id,user_id','active',6,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_merge_drawer','A','admin','Merge drawer','src_id,dst_id','active',7,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_archive_wing','A','admin','Archive wing','wing_id','active',8,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_restore_wing','A','admin','Restore wing','wing_id','active',8,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_reindex_search','A','admin','Reindex search','wing_id','active',7,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_quota_set','A','admin','Set quota','wing_id,bytes','active',8,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_audit_log','A','admin','Audit log','filter','active',8,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_backup','A','admin','Backup','wing_id','active',9,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_restore','A','admin','Restore from backup','backup_id','active',9,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_mcp_initialize','A','admin','MCP initialize','client_info','active',7,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_mcp_health','A','admin','MCP health','—','active',9,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('mempalace_mcp_ping','A','admin','MCP ping','—','active',9,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('index_repository','B','index','Index repository','repo_path,mode','active',3,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('list_projects','B','index','List projects','—','active',7,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('index_status','B','index','Index status','project_id','active',4,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('delete_project','B','index','Delete project','project_id','active',7,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('search_graph','B','query','Search graph','label,name','active',2,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('trace_path','B','query','Trace call path','target,depth','active',2,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('query_graph','B','query','Cypher query','cypher,params','active',3,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('search_code','B','query','Code text search','query,scope','active',3,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('get_code_snippet','B','query','Get snippet','file,line_range','active',4,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('get_graph_schema','B','query','Graph schema','—','active',6,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('detect_changes','B','analysis','Detect changes','git_diff','active',1,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('get_architecture','B','analysis','Get architecture','scope','active',3,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('manage_adr','B','analysis','ADR CRUD','op,adr','active',4,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00'),
    ('ingest_traces','B','analysis','Ingest traces','trace_bundle','active',5,'1.0.0','2026-07-12 00:00:00','2026-07-12 00:00:00');

COMMIT;
